from .frozen_constraints import FROZEN_CONSTRAINTS, verify_constraints_integrity
from .candidate_framework import CANDIDATE_FRAMEWORK, IMMUTABLE_FIELDS
from .writing_rules import WRITING_RULES
from .education_decision_tree import decide_education
