#!/usr/bin/env python3
"""
md_to_tex.py — Deterministic Markdown → LaTeX (XeLaTeX) converter.

Parses the fixed-structure resume Markdown files and emits LaTeX
matching the docx reference style (Helvetica Neue, blue section headings,
structured job entries with sub-project headings).

Supports progressive compression levels (0-3) to fit content within 2 pages:
  Level 0: Default (two-line header, two-line job, normal spacing)
  Level 1: Single-line header (name | contact on one line)
  Level 2: Level 1 + single-line job titles
  Level 3: Level 2 + compact spacing (reduced margins, tighter bullets)

Usage:
    python3 md_to_tex.py resumes/03_Mobile_Platform_Engineer_Resume.md
    python3 md_to_tex.py resumes/03_Mobile_Platform_Engineer_Resume.md --output output/tex/
    python3 md_to_tex.py resumes/*.md --output output/tex/
    python3 md_to_tex.py resumes/*.md --output output/tex/ --level 2
"""

import argparse
import os
import re
import sys
from pathlib import Path

# ────────────────────────────────────────────────────────────
# LaTeX preamble — XeLaTeX + Helvetica Neue, docx-matching style
# ────────────────────────────────────────────────────────────

def build_preamble(level: int = 0) -> str:
    """根据压缩级别生成 LaTeX preamble。"""
    compact = level >= 3

    # 间距参数
    if compact:
        top_margin = "0.48in"
        bottom_margin = "0.38in"
        section_before = "8pt"
        section_after = "3pt"
        itemsep = "1.5pt"
    else:
        top_margin = "0.50in"
        bottom_margin = "0.42in"
        section_before = "10pt"
        section_after = "4pt"
        itemsep = "2pt"

    mode_comment = f" (compress level {level})" if level > 0 else ""

    return rf"""%-------------------------
% Resume in LaTeX — XeLaTeX build{mode_comment}
% Auto-generated by md_to_tex.py
%-------------------------

\documentclass[letterpaper,12pt]{{article}}

\usepackage{{fontspec}}
\setmainfont{{Helvetica Neue}}

\usepackage{{titlesec}}
\usepackage{{xcolor}}
\usepackage{{enumitem}}
\usepackage[hidelinks]{{hyperref}}
\usepackage{{fancyhdr}}
\usepackage{{tabularx}}
\usepackage{{geometry}}
\usepackage{{needspace}}
\usepackage{{array}}
\usepackage[final]{{microtype}}

\geometry{{
  letterpaper,
  top={top_margin},
  bottom={bottom_margin},
  left=0.50in,
  right=0.50in
}}

\pagestyle{{fancy}}
\fancyhf{{}}
\fancyfoot{{}}
\renewcommand{{\headrulewidth}}{{0pt}}
\renewcommand{{\footrulewidth}}{{0pt}}

\urlstyle{{same}}
\raggedbottom
\raggedright
\setlength{{\tabcolsep}}{{0in}}
\setlength{{\parindent}}{{0pt}}

% ─── 孤行防护 ───
\widowpenalty=10000
\clubpenalty=10000

% ─── 防止单词孤行（行末单独一个词）───
\tolerance=200
\emergencystretch=2em

% ─── 颜色定义 (匹配 docx) ───
\definecolor{{sectionblue}}{{HTML}}{{2B579A}}
\definecolor{{locgray}}{{HTML}}{{666666}}
\definecolor{{dategray}}{{HTML}}{{444444}}

% ─── Section 标题: 12pt bold 蓝色 + 蓝色下划线 ───
\titleformat{{\section}}{{
  \fontsize{{13pt}}{{15.6pt}}\selectfont\bfseries\color{{sectionblue}}\raggedright
}}{{}}{{0em}}{{}}[\color{{sectionblue}}\titlerule]
\titlespacing*{{\section}}{{0pt}}{{{section_before}}}{{{section_after}}}

% ─── Bullet 列表配置 ───
\newcommand{{\resumeItemListStart}}{{
  \begin{{itemize}}[leftmargin=0.15in, labelsep=0.08in, topsep=2pt, parsep=0pt, partopsep=0pt, itemsep={itemsep}]
}}
\newcommand{{\resumeItemListEnd}}{{\end{{itemize}}}}

\newcommand{{\resumeItem}}[1]{{
  \item{{\fontsize{{10.5pt}}{{12.6pt}}\selectfont #1}}
}}

%-------------------------------------------
"""


# ────────────────────────────────────────────────────────────
# LaTeX escaping
# ────────────────────────────────────────────────────────────

def _escape_raw(text: str) -> str:
    """Escape LaTeX special characters in a plain-text segment (no bold markers)."""
    text = text.replace('\\', r'\textbackslash{}')
    text = text.replace('&', r'\&')
    text = text.replace('%', r'\%')
    text = text.replace('$', r'\$')
    text = text.replace('#', r'\#')
    text = text.replace('_', r'\_')
    text = text.replace('{', r'\{')
    text = text.replace('}', r'\}')
    text = text.replace('~', r'\textasciitilde{}')
    text = text.replace('^', r'\textasciicircum{}')
    # en-dash / em-dash
    text = text.replace('–', '--')
    text = text.replace('—', '---')
    # math symbols
    text = text.replace('≤', r'$\leq$')
    text = text.replace('≥', r'$\geq$')
    text = text.replace('<', r'\textless{}')
    text = text.replace('>', r'\textgreater{}')
    return text


def escape_latex(text: str) -> str:
    """Escape LaTeX special characters while converting **bold** to \\textbf{}.

    Splits text on **bold** markers first, then escapes each segment
    independently.
    """
    parts = re.split(r'\*\*(.+?)\*\*', text)

    result = []
    for i, part in enumerate(parts):
        if i % 2 == 0:
            result.append(_escape_raw(part))
        else:
            result.append(r'\textbf{' + _escape_raw(part) + '}')

    return ''.join(result)


# ────────────────────────────────────────────────────────────
# Markdown parser — state machine
# ────────────────────────────────────────────────────────────

def _strip_bullet(line: str) -> str | None:
    """Strip '* ' or '- ' prefix from a bullet line. Returns None if not a bullet."""
    if line.startswith('* '):
        return line[2:]
    if line.startswith('- '):
        return line[2:]
    return None


def _is_subproject_heading(line: str) -> str | None:
    """Detect sub-project heading lines. Returns the title text or None.

    Formats:
      **_Title here_**          → bold+italic
      **Sub-project: Title**    → bold with prefix
      **_Core Contributions:_** → bold+italic
    """
    # **_Title_** (bold + italic)
    m = re.match(r'^\*\*_(.*?)_\*\*$', line)
    if m:
        return m.group(1)
    # **Sub-project: Title** (bold only)
    m = re.match(r'^\*\*Sub-project:\s*(.+?)\*\*$', line)
    if m:
        return m.group(1)
    # **Project: Title** (resume_pipeline legacy format)
    m = re.match(r'^\*\*Project:\s*(.+?)\*\*$', line)
    if m:
        return m.group(1)
    return None


class ResumeParser:
    """Parses a resume .md file into structured sections."""

    def __init__(self, md_text: str):
        self.lines = md_text.splitlines()
        self.idx = 0
        self.name = ""
        self.email = ""
        self.phone = ""
        self.summary_bullets = []          # list of bullet strings
        self.work_experience = []          # list of dicts (see _parse_one_experience)
        self.projects = []                 # list of (title, [bullets])
        self.skills = []                   # list of (category, items_str)
        self.education = []                # list of (degree, institution, period)
        self.additional = []               # list of bullet strings

    def parse(self):
        """Main entry: walk through the file line by line."""
        while self.idx < len(self.lines):
            line = self.lines[self.idx].strip()

            if line.startswith('# ') and not line.startswith('## '):
                heading = line[2:].strip()
                if heading == 'Professional Summary':
                    # 文件 01/02 格式: # Professional Summary 直接跟 bullets
                    self._parse_summary()
                else:
                    # 文件 03+ 格式: # Candidate Name
                    self.name = heading
            elif self._looks_like_contact(line):
                self._parse_contact_line(line)
            elif line == '## Professional Summary':
                self._parse_summary()
            elif line == '## Work Experience' or line == '## Experience':
                self._parse_experience()
            elif line == '## Projects':
                self._parse_projects()
            elif line == '## Skills':
                self._parse_skills()
            elif line == '## Education':
                self._parse_education()
            elif line in {'## Additional Information', '## Achievement', '## Achievements'}:
                self._parse_additional()

            self.idx += 1

    def _looks_like_contact(self, line: str) -> bool:
        if not line:
            return False
        if '@' in line and '|' in line:
            return True
        return False

    def _parse_contact_line(self, line: str) -> None:
        parts = [p.strip() for p in re.split(r'\s*\|\s*', line) if p.strip()]
        for part in parts:
            if re.match(r'^[\w\.\+\-]+@[\w\.\-]+\.\w+$', part):
                self.email = part
            elif re.match(r'^\+?[\d\-\s\(\)\.]{7,}$', part):
                self.phone = part

    def _parse_summary(self):
        """Collect bullet items after Professional Summary heading."""
        self.idx += 1
        while self.idx < len(self.lines):
            line = self.lines[self.idx].strip()
            if line.startswith('## ') or line == '---':
                self.idx -= 1
                break
            bullet = _strip_bullet(line)
            if bullet:
                self.summary_bullets.append(bullet)
            self.idx += 1

    def _parse_experience(self):
        """Parse ### headings under Work Experience."""
        self.idx += 1
        while self.idx < len(self.lines):
            line = self.lines[self.idx].strip()
            if line.startswith('## ') or (line == '---' and not self._next_is_subheading()):
                self.idx -= 1
                break
            if line.startswith('### '):
                self._parse_one_experience()
            else:
                self.idx += 1

    def _next_is_subheading(self):
        """Check if after a --- there's still a ### (i.e. still in same section)."""
        j = self.idx + 1
        while j < len(self.lines):
            l = self.lines[j].strip()
            if l.startswith('### '):
                return True
            if l.startswith('## ') or (l and not l.startswith('#') and l != '---'):
                return False
            j += 1
        return False

    def _parse_one_experience(self):
        """Parse a single ### work experience entry.

        Returns dict:
          title, date, company_team, location, items
        where items is a list of ("bullet", text) or ("subproject", title).
        """
        heading = self.lines[self.idx].strip()[4:]  # remove "### "
        parts = [p.strip() for p in heading.split('|')]

        if len(parts) >= 3:
            title = parts[0]
            company_team = parts[1]
            location = parts[2]
        elif len(parts) == 2:
            title = parts[0]
            company_team = parts[1]
            location = ""
        else:
            title = heading
            company_team = ""
            location = ""

        # Next non-empty line should be **Date** or legacy *Date | Location*
        self.idx += 1
        date_str = ""
        while self.idx < len(self.lines):
            line = self.lines[self.idx].strip()
            if line:
                m = re.match(r'^\*\*(.+?)\*\*$', line)
                if m:
                    date_str = m.group(1)
                elif (
                    line.startswith('*')
                    and line.endswith('*')
                    and not line.startswith('* ')
                    and not line.startswith('**')
                ):
                    inner = line.strip('*').strip()
                    if '|' in inner:
                        date_parts = [part.strip() for part in inner.split('|', 1)]
                        date_str = date_parts[0]
                        if len(date_parts) > 1 and not location:
                            location = date_parts[1]
                    else:
                        date_str = inner
                else:
                    date_str = line
                self.idx += 1
                break
            self.idx += 1

        # Collect items: bullets and sub-project headings
        items = self._collect_items()
        self.work_experience.append({
            'title': title,
            'date': date_str,
            'company': company_team,
            'location': location,
            'items': items,
        })

    def _collect_items(self):
        """Collect bullet lines and sub-project headings until next heading or section."""
        items = []
        while self.idx < len(self.lines):
            line = self.lines[self.idx].strip()
            if line.startswith('### ') or line.startswith('## ') or line == '---':
                break
            # 检查子项目标题
            subproject = _is_subproject_heading(line)
            if subproject is not None:
                items.append(('subproject', subproject))
                self.idx += 1
                continue
            # 检查 scope (引用符 > )
            if line.startswith('> '):
                items.append(('scope', line[2:].strip()))
                self.idx += 1
                continue
            # 检查 bullet
            bullet = _strip_bullet(line)
            if bullet is not None:
                items.append(('bullet', bullet))
                self.idx += 1
                continue
            # 空行或其他行，跳过
            self.idx += 1
        return items

    def _parse_projects(self):
        """Parse ### headings under Projects."""
        self.idx += 1
        while self.idx < len(self.lines):
            line = self.lines[self.idx].strip()
            if line.startswith('## ') or (line == '---' and not self._next_is_subheading()):
                self.idx -= 1
                break
            if line.startswith('### '):
                self._parse_one_project()
            else:
                self.idx += 1

    def _parse_one_project(self):
        """Parse a single project entry."""
        title = self.lines[self.idx].strip()[4:]
        self.idx += 1
        bullets = []
        while self.idx < len(self.lines):
            line = self.lines[self.idx].strip()
            if line.startswith('### ') or line.startswith('## ') or line == '---':
                break
            # 检查 scope (引用符 > )
            if line.startswith('> '):
                bullets.append(('scope', line[2:].strip()))
                self.idx += 1
                continue
            bullet = _strip_bullet(line)
            if bullet is not None:
                bullets.append(bullet)
            self.idx += 1
        self.projects.append((title, bullets))

    def _parse_skills(self):
        """Parse skill lines: **Category:** items (with or without * prefix)."""
        self.idx += 1
        while self.idx < len(self.lines):
            line = self.lines[self.idx].strip()
            if line.startswith('## ') or line == '---':
                self.idx -= 1
                break
            # 去掉可能的 * 前缀
            check = line
            if check.startswith('* '):
                check = check[2:]
            if check.startswith('- '):
                check = check[2:]
            m = re.match(r'^\*\*(.+?)[:\uff1a]\*\*\s*(.+)$', check)
            if m:
                self.skills.append((m.group(1), m.group(2)))
            self.idx += 1

    def _parse_education(self):
        """Parse the markdown table under Education."""
        self.idx += 1
        # Skip table header and separator
        while self.idx < len(self.lines):
            line = self.lines[self.idx].strip()
            if line.startswith('|') and '---' in line:
                self.idx += 1
                break
            if line.startswith('|'):
                self.idx += 1
                continue
            if not line:
                self.idx += 1
                continue
            if line == '---' or line.startswith('## '):
                self.idx -= 1
                return
            self.idx += 1

        # Parse data rows
        while self.idx < len(self.lines):
            line = self.lines[self.idx].strip()
            if not line.startswith('|'):
                if line == '---' or line.startswith('## ') or not line:
                    self.idx -= 1
                    break
                self.idx += 1
                continue
            cells = [c.strip() for c in line.split('|')[1:-1]]
            if len(cells) >= 3:
                self.education.append((cells[0], cells[1], cells[2]))
            self.idx += 1

    def _parse_additional(self):
        """Parse bullet items under Additional Information."""
        self.idx += 1
        while self.idx < len(self.lines):
            line = self.lines[self.idx].strip()
            if line.startswith('## ') or line == '---':
                self.idx -= 1
                break
            bullet = _strip_bullet(line)
            if bullet is not None:
                self.additional.append(bullet)
            self.idx += 1


# ────────────────────────────────────────────────────────────
# LaTeX emitter
# ────────────────────────────────────────────────────────────

def emit_latex(parser: ResumeParser, level: int = 0) -> str:
    """Convert parsed resume into a complete LaTeX document string.

    level:
      0 = 默认（两行 header + 两行 job + 正常间距）
      1 = 单行 header（姓名 | 联系方式）
      2 = 单行 header + 单行 job（Title | Company | City | Date）
      3 = 单行 header + 单行 job + 紧凑间距
    """
    compact = level >= 3
    single_header = level >= 1
    single_job = level >= 2
    job_vspace = r'\vspace{4pt}' if compact else r'\vspace{6pt}'
    sub_vspace = r'\vspace{2pt}' if compact else r'\vspace{4pt}'

    parts = [build_preamble(level), r'\begin{document}', '']

    # ─── HEADING ───
    parts.append(r'\begin{center}')
    if single_header:
        # 单行: 姓名(14pt bold) | 联系方式(9.5pt)
        header_items = []
        if parser.name:
            header_items.append(r'{\fontsize{16pt}{19.2pt}\selectfont\bfseries ' +
                                escape_latex(parser.name) + r'}')
        contact_parts = _build_contact_parts(parser)
        if contact_parts:
            header_items.append(r'{\fontsize{10.5pt}{12.6pt}\selectfont ' +
                                r' \hspace{0.4em}\textbar\hspace{0.4em} '.join(contact_parts) +
                                r'}')
        if header_items:
            parts.append(r'  \parbox{\textwidth}{\centering ' +
                         r' \hspace{0.4em}\textbar\hspace{0.4em} '.join(header_items) +
                         r'}')
    else:
        # 两行: 姓名 16pt 一行 + 联系方式 9.5pt 一行
        if parser.name:
            parts.append(r'  {\fontsize{18pt}{21.6pt}\selectfont\bfseries ' +
                         escape_latex(parser.name) + r'} \\[1pt]')
        contact_parts = _build_contact_parts(parser)
        if contact_parts:
            parts.append(r'  {\fontsize{10.5pt}{12.6pt}\selectfont ' +
                         r' \hspace{0.4em}\textbar\hspace{0.4em} '.join(contact_parts) +
                         r'}')
    parts.append(r'\end{center}')
    parts.append('')

    # ─── PROFESSIONAL SUMMARY ───
    if parser.summary_bullets:
        parts.append(r'\section{Professional Summary}')
        parts.append(r'\resumeItemListStart')
        for bullet in parser.summary_bullets:
            parts.append(r'  \resumeItem{' + escape_latex(bullet) + '}')
        parts.append(r'\resumeItemListEnd')
        parts.append('')

    # ─── WORK EXPERIENCE ───
    if parser.work_experience:
        parts.append(r'\section{Work Experience}')
        for job in parser.work_experience:
            # needspace: 保留 header + 至少 1 行 bullet，但不要太大以免大片留白
            parts.append(r'\needspace{2\baselineskip}')
            parts.append(job_vspace)

            title_tex = r'\textbf{\color{sectionblue}' + escape_latex(job['title']) + '}'
            company_tex = r'{\color{sectionblue}' + escape_latex(job['company']) + '}' if job['company'] else ''
            location_tex = (r'{\color{sectionblue}' + escape_latex(job['location']) + '}') if job['location'] else ''
            date_tex = (r'{\color{sectionblue}' + escape_latex(job['date']) + '}') if job['date'] else ''

            # Single line: Job Title | Company · Team | Location | Dates
            job_line_parts = [title_tex]
            if company_tex:
                job_line_parts.append(company_tex)
            if location_tex:
                job_line_parts.append(location_tex)
            if date_tex:
                job_line_parts.append(date_tex)
            
            parts.append(r'{\fontsize{11.5pt}{13.8pt}\selectfont\color{sectionblue} ' + 
                         r' \hspace{0.4em}\textbar\hspace{0.4em} '.join(job_line_parts) + 
                         r'}\par')

            parts.append(r'\vspace{2pt}')

            # 遍历 items: 子项目标题 + bullets
            in_bullet_list = False
            for item_type, item_text in job['items']:
                if item_type == 'subproject':
                    if in_bullet_list:
                        parts.append(r'\resumeItemListEnd')
                        in_bullet_list = False
                    parts.append(r'\needspace{2\baselineskip}')
                    parts.append(sub_vspace)
                    parts.append(r'{\fontsize{10.5pt}{12.6pt}\selectfont\textbf{\textit{' +
                                 escape_latex(item_text) + r'}}}\par')
                    parts.append(r'\vspace{1pt}')
                elif item_type == 'scope':
                    if in_bullet_list:
                        parts.append(r'\resumeItemListEnd')
                        in_bullet_list = False
                    parts.append(r'\vspace{1pt}')
                    # Style: 9pt, italics, no prefix. Preserve internal bolding.
                    parts.append(r'{\fontsize{9pt}{10.8pt}\selectfont\textit{' +
                                 escape_latex(item_text) + r'}}\par')
                    parts.append(r'\vspace{2pt}')
                elif item_type == 'bullet':
                    if not in_bullet_list:
                        parts.append(r'\resumeItemListStart')
                        in_bullet_list = True
                    parts.append(r'  \resumeItem{' + escape_latex(item_text) + '}')
            if in_bullet_list:
                parts.append(r'\resumeItemListEnd')
            parts.append('')

    # ─── PROJECTS ───
    if parser.projects:
        parts.append(r'\section{Projects}')
        for title, bullets in parser.projects:
            parts.append(r'\vspace{4pt}')
            parts.append(r'{\fontsize{11pt}{13.2pt}\selectfont\textbf{' + escape_latex(title) + r'}}\par')
            for item_type, item_text in bullets:
                if item_type == 'scope':
                    if in_bullet_list:
                        parts.append(r'\resumeItemListEnd')
                        in_bullet_list = False
                    parts.append(r'\vspace{1pt}')
                    parts.append(r'{\fontsize{9pt}{10.8pt}\selectfont\textit{' +
                                 escape_latex(item_text) + r'}}\par')
                    parts.append(r'\vspace{2pt}')
                else: # bullet
                    if not in_bullet_list:
                        parts.append(r'\resumeItemListStart')
                        in_bullet_list = True
                    parts.append(r'  \resumeItem{' + escape_latex(item_text) + '}')
            parts.append('')

    # ─── SKILLS ───
    if parser.skills:
        parts.append(r'\section{Skills}')
        parts.append(r'\resumeItemListStart')
        for cat, items in parser.skills:
            parts.append(r'  \resumeItem{\textbf{' + escape_latex(cat) + ':} ' +
                         escape_latex(items) + '}')
        parts.append(r'\resumeItemListEnd')
        parts.append('')

    # ─── EDUCATION ───
    if parser.education:
        parts.append(r'\section{Education}')
        parts.append(r'\resumeItemListStart')
        for degree, institution, period in parser.education:
            parts.append(
                r'  \resumeItem{\textbf{' + escape_latex(degree) + r'} ' +
                r' \hspace{0.4em}\textbar\hspace{0.4em} ' + escape_latex(institution) +
                r' \hspace{0.4em}\textbar\hspace{0.4em} ' + escape_latex(period) + '}'
            )
        parts.append(r'\resumeItemListEnd')
        parts.append('')

    # ─── ADDITIONAL INFORMATION ───
    if parser.additional:
        parts.append(r'\section{Additional Information}')
        parts.append(r'\resumeItemListStart')
        for item in parser.additional:
            parts.append(r'  \resumeItem{' + escape_latex(item) + '}')
        parts.append(r'\resumeItemListEnd')
        parts.append('')

    parts.append(r'\end{document}')
    return '\n'.join(parts)


def _build_contact_parts(parser: ResumeParser) -> list[str]:
    """构建联系方式 LaTeX 片段列表"""
    contact_parts = []
    if parser.email:
        contact_parts.append(
            r'\href{mailto:' + parser.email + r'}{\underline{' + escape_latex(parser.email) + r'}}'
        )
    if parser.phone:
        phone_href = re.sub(r'[\s\-\(\)\.]', '', parser.phone)
        contact_parts.append(
            r'\href{tel:' + phone_href + r'}{\underline{' + escape_latex(parser.phone) + r'}}'
        )
    return contact_parts


# ────────────────────────────────────────────────────────────
# CLI
# ────────────────────────────────────────────────────────────

def convert_file(md_path: str, output_dir: str | None = None,
                 compact: bool = False, level: int | None = None) -> str:
    """Convert a single .md file to .tex, return the output path.

    level: 压缩级别 0-3。如果指定 compact=True 且 level=None，则使用 level=3。
    """
    if level is None:
        level = 3 if compact else 0

    md_path = Path(md_path)
    with open(md_path, 'r', encoding='utf-8') as f:
        md_text = f.read()

    parser = ResumeParser(md_text)
    parser.parse()
    tex_content = emit_latex(parser, level=level)

    if output_dir:
        out_dir = Path(output_dir)
        out_dir.mkdir(parents=True, exist_ok=True)
        out_path = out_dir / md_path.with_suffix('.tex').name
    else:
        out_path = md_path.with_suffix('.tex')

    with open(out_path, 'w', encoding='utf-8') as f:
        f.write(tex_content)

    return str(out_path)


def main():
    ap = argparse.ArgumentParser(description='Convert resume Markdown to LaTeX (XeLaTeX)')
    ap.add_argument('files', nargs='+', help='Markdown resume file(s)')
    ap.add_argument('--output', '-o', default=None, help='Output directory for .tex files')
    ap.add_argument('--compact', action='store_true', help='Use compact spacing (level 3)')
    ap.add_argument('--level', type=int, default=None, choices=[0, 1, 2, 3],
                    help='Compression level: 0=default, 1=single header, 2=+single job, 3=+compact spacing')
    args = ap.parse_args()

    level = args.level
    if level is None and args.compact:
        level = 3

    for md_file in args.files:
        try:
            out = convert_file(md_file, args.output, level=level)
            print(f"✅  {md_file} → {out}")
        except Exception as e:
            print(f"❌  {md_file}: {e}", file=sys.stderr)
            sys.exit(1)


if __name__ == '__main__':
    main()
