"""Narrative generation for canonical skills and merged narrative groups."""

from __future__ import annotations

from .taxonomy import CATEGORY_ORDER

CATEGORY_DEFAULTS = {
    "Programming Languages": (
        "{skill} 是一种编程语言，通常用于实现业务逻辑、自动化流程和生产环境应用代码。",
        "团队可以用 {skill} 开发处理交易、用户事件或内部运营数据的服务与批处理任务，支撑日常业务运转。",
    ),
    "Backend & APIs": (
        "{skill} 是一种后端技术，常用于提供服务接口、打通系统之间的数据流，并组织应用执行流程。",
        "团队可以用 {skill} 连接支付、账户、库存或工单系统，让多个业务平台之间的数据与操作保持同步。",
    ),
    "Frontend & UI": (
        "{skill} 是一种前端或客户端技术，主要用于构建用户直接交互的页面和界面。",
        "团队可以用 {skill} 搭建内部看板或面向客户的操作页面，让用户查看记录、提交动作并跟踪状态变化。",
    ),
    "Data & Analytics": (
        "{skill} 是一种数据与分析工具，常用于处理、检查和汇报运营或产品数据。",
        "团队可以用 {skill} 产出 KPI 报表、完成交易对账，或生成周期性分析结果来支持业务决策。",
    ),
    "AI / ML": (
        "{skill} 是一种 AI 或机器学习技术，常用于模型训练、推理执行，或提升检索与生成效果。",
        "团队可以用 {skill} 做工单分类、搜索排序、文档总结，或辅助运营人员更快处理大量业务案例。",
    ),
    "Cloud / DevOps / Infrastructure": (
        "{skill} 是一种基础设施或交付技术，主要用于部署、运维和扩展生产系统。",
        "团队可以用 {skill} 自动化发布流程、配置运行环境，或保障关键业务服务在流量高峰期依然稳定运行。",
    ),
    "Databases / Storage / Streaming": (
        "{skill} 是一种存储或数据流转技术，常用于持久化业务记录、支持查询访问，或在系统之间传递事件数据。",
        "团队可以用 {skill} 保存应用状态、归档业务文件，或把运营事件实时传给下游监控与处理流程。",
    ),
    "Architecture / Systems": (
        "{skill} 是一种系统设计相关能力，用于构建可靠软件并分析系统在规模增长时的运行行为。",
        "团队在设计需要兼顾性能、准确性和可维护性的业务平台时，通常会应用 {skill} 来做技术取舍。",
    ),
    "Quality & Workflow": (
        "{skill} 是一种质量保障或交付协作实践，用于提升研发执行效率并减少缺陷。",
        "团队可以用 {skill} 做代码评审、发布验证，或组织日常交付流程，让产品与运营需求更稳定地落地。",
    ),
}

SKILL_OVERRIDES = {
    "Python": (
        "Python 是一种通用编程语言，广泛用于后端服务、数据流程、自动化脚本和应用型机器学习开发。",
        "团队可以用 Python 编写 ETL 任务、内部 API 和模型评估脚本，支持日常运营、分析与报表流程。",
    ),
    "SQL": (
        "SQL 是关系型系统中最核心的查询语言，用于提取、聚合和校验结构化数据。",
        "团队可以用 SQL 做结算对账、漏斗转化分析，或生成财务和运营每天要看的 KPI 明细表。",
    ),
    "Docker": (
        "Docker 通过容器封装应用及其依赖，使软件能在不同环境中保持一致运行。",
        "团队可以用 Docker 把同一个服务镜像从本地测试一路部署到预发和生产，减少环境不一致导致的问题。",
    ),
    "Kubernetes": (
        "Kubernetes 是容器编排平台，负责处理部署、扩缩容、健康检查和服务发现。",
        "团队可以用 Kubernetes 保障内部 API 或批处理平台在流量变化和定时任务波动下依旧稳定运行。",
    ),
    "REST APIs": (
        "REST APIs 是基于 HTTP 的接口形式，便于不同应用以标准化方式交换数据和触发业务动作。",
        "团队可以用 REST APIs 打通订单、计费、CRM 和客服系统，让关键业务更新自动在多系统间流转。",
    ),
    "PostgreSQL": (
        "PostgreSQL 是常见的关系型数据库，适合承载事务数据、复杂查询和稳定的应用存储。",
        "团队可以用 PostgreSQL 存储账户信息、流程状态和审计记录，支撑内部运营系统的核心能力。",
    ),
    "Kafka": (
        "Kafka 是分布式事件流平台，用于发布、缓冲和消费高吞吐的数据流。",
        "团队可以用 Kafka 把订单、支付或风控事件从源系统送入监控、告警和分析链路中。",
    ),
    "Pandas": (
        "Pandas 是 Python 生态中的表格数据处理库，适合做清洗、合并和分析。",
        "团队可以用 Pandas 准备周度业务复盘、校验新指标口径，或在进入正式数据管道前先排查异常。",
    ),
    "Spark SQL": (
        "Spark SQL 是面向大规模结构化数据的分布式查询引擎，支持类 SQL 方式处理海量数据。",
        "团队可以用 Spark SQL 汇总点击流、物流或交易数据，为每日经营报表提供基础结果。",
    ),
    "Hive": (
        "Hive 是常见的数据仓库技术，用于在分布式存储上组织和查询大规模数据集。",
        "团队可以用 Hive 构建供给、增长或商家表现分析所需的批量数据表。",
    ),
    "Java": (
        "Java 是成熟的生产级编程语言，广泛用于后端服务、企业系统和大型代码库开发。",
        "团队可以用 Java 实现订单路由、账户流程或需要长期维护的集成服务。",
    ),
    "gRPC": (
        "gRPC 是高性能的远程调用框架，适合后端系统之间进行类型明确、低延迟的通信。",
        "团队可以用 gRPC 连接搜索、推荐或风控等内部微服务，支撑对实时性要求较高的业务流程。",
    ),
    "AWS": (
        "AWS 是云平台，提供计算、存储、网络和各类托管服务，适合承载生产应用。",
        "团队可以用 AWS 托管 API、定时数据任务和对象存储，支撑日常业务系统运行。",
    ),
    "Redis": (
        "Redis 是内存型数据存储，常用于缓存、队列、会话状态和高频键值查询。",
        "团队可以用 Redis 加速看板加载、限流控制或面向客户平台中的流程状态读取。",
    ),
    "RAG": (
        "RAG 将检索与生成结合起来，让模型基于知识库或文档内容给出有依据的回答。",
        "团队可以用 RAG 帮助分析师检索制度、合同或历史工单，并生成带引用依据的答复草稿。",
    ),
    "AWS Bedrock": (
        "AWS Bedrock 提供对基础模型及相关组件的托管访问能力，适合企业级生成式 AI 场景。",
        "团队可以用 AWS Bedrock 搭建内部 Copilot，用于文档总结、制度问答或审核流程辅助。",
    ),
    "ETL": (
        "ETL 是抽取、转换、加载数据的流程，用于把原始数据整理成下游系统可直接使用的形式。",
        "团队可以用 ETL 将订单、商家或财务原始记录加工成看板、报表和管控系统可用的数据表。",
    ),
    "MySQL": (
        "MySQL 是常用的关系型数据库，适合存储事务型应用和内部工具的数据。",
        "团队可以用 MySQL 支撑运营看板，实时记录案件、任务和审核结果等业务信息。",
    ),
    "A/B Testing": (
        "A/B Testing 是一种实验方法，用于比较不同方案并判断哪种改动在业务指标上表现更好。",
        "团队可以用 A/B Testing 验证新注册流程、排序模型或促销策略，再决定是否全量上线。",
    ),
    "S3": (
        "S3 是 AWS 的对象存储服务，适合长期保存文件、数据集备份和各类产物。",
        "团队可以用 S3 存储简历、发票、日志或模型文件，供下游任务持续读取和处理。",
    ),
    "Airflow": (
        "Airflow 是工作流编排工具，可以用代码方式管理定时任务和上下游依赖。",
        "团队可以用 Airflow 驱动收入看板刷新、异常检查和下游通知等日常数据作业。",
    ),
    "CI/CD": (
        "CI/CD 用于自动化完成代码校验与部署，让变更可以更稳定地进入发布流程。",
        "团队可以用 CI/CD 在每次提交后自动跑测试，并把通过验证的构建按节奏推到预发和生产环境。",
    ),
    "GitHub Actions": (
        "GitHub Actions 是基于代码仓库的工作流自动化平台，适合执行测试、检查和部署步骤。",
        "团队可以用 GitHub Actions 在 PR 合并后自动完成代码检查、集成测试和发布产物生成。",
    ),
    "Microservices": (
        "Microservices 是一种架构模式，把系统拆分成多个可以独立部署和扩展的小服务。",
        "团队可以用微服务拆开计费、身份、搜索和通知模块，让不同业务能力独立演进和扩容。",
    ),
    "Flask": (
        "Flask 是轻量级 Python Web 框架，适合快速搭建 API 和内部服务。",
        "团队可以用 Flask 上线内部审核工具或指标查询接口，服务运营和分析同学的日常工作。",
    ),
    "LLM": (
        "LLM 指大语言模型，能够处理生成、分类、总结和改写等自然语言任务。",
        "团队可以用 LLM 总结工单、起草调查记录，或帮助员工更快检索大量文档资料。",
    ),
    "scikit-learn": (
        "scikit-learn 是 Python 中常用的机器学习库，适合做传统模型训练、特征处理和效果评估。",
        "团队可以用 scikit-learn 预测流失风险、识别异常，或在上线前评估一个新的分类模型。",
    ),
    "Machine Learning": (
        "Machine Learning 是利用数据训练模型，从而完成预测、排序或自动化决策的方法。",
        "团队可以用机器学习做需求预测、线索排序、欺诈识别或客服队列优先级分配。",
    ),
    "Git": (
        "Git 是版本控制系统，用于追踪代码变更并支持团队协作开发。",
        "团队可以用 Git 管理功能开发、隔离缺陷修复，并保留一份清晰可靠的生产变更历史。",
    ),
    "React": (
        "React 是用于构建交互式界面的前端库，强调组件化开发和页面状态管理。",
        "团队可以用 React 搭建内部运营门户，让用户查看账户、处理告警并执行操作动作。",
    ),
}

MERGED_GROUPS = [
    {
        "group_id": "programming_generalists",
        "category": "Programming Languages",
        "skills": ["Go", "JavaScript", "C++", "Scala", "TypeScript", "R", "C#", "PHP", "Ruby", "Rust", "Kotlin", "Swift", "MATLAB", "VB.NET"],
        "common_introduction": "这组技术栈都属于通用编程语言，核心价值是承载业务逻辑、自动化任务和生产环境代码实现。",
        "common_business_scenario": "团队通常会用它们开发服务接口、离线任务、数据处理流程或业务系统模块，支撑日常功能交付和系统演进。",
    },
    {
        "group_id": "backend_frameworks",
        "category": "Backend & APIs",
        "skills": ["Node.js", "Spring Boot", "Spring", "Express", ".NET", "ASP.NET", "Rails", "GraphQL", "FastAPI", "Django", "NestJS", ".NET / C#", "ASP.NET MVC"],
        "common_introduction": "这组技术栈主要用于后端应用开发与接口组织，适合构建服务层、业务编排层和系统集成层。",
        "common_business_scenario": "团队通常会用它们承接订单、账户、支付、工单或内部运营平台的接口请求，连接上游页面与下游业务系统。",
    },
    {
        "group_id": "frontend_stack",
        "category": "Frontend & UI",
        "skills": ["Angular", "CSS", "HTML", "Vue", "HTML5", "Vite", "CSS3", "Next.js", "Android SDK", "Jetpack Compose", "Material Design", "Tailwind", "Webpack"],
        "common_introduction": "这组技术栈主要服务于前端界面和客户端体验建设，用于实现页面结构、视觉样式、交互逻辑和构建流程。",
        "common_business_scenario": "团队通常会用它们搭建内部工作台、运营看板、管理后台或面向客户的交互页面，承接信息展示与操作提交流程。",
    },
    {
        "group_id": "analytics_platforms",
        "category": "Data & Analytics",
        "skills": ["Jupyter", "Spark", "Tableau", "Data Pipelines", "Matplotlib", "Snowflake", "Databricks", "BigQuery", "NumPy", "Power BI", "dbt", "Hadoop", "Anomaly Detection", "Dashboard Automation", "Experiment Design", "Forecasting", "KPI Measurement", "Looker", "Time Series Analysis"],
        "common_introduction": "这组技术栈都围绕数据处理、分析建模、报表展示和指标体系建设展开，适合支撑数据驱动型业务决策。",
        "common_business_scenario": "团队通常会用它们搭建分析环境、生成经营报表、监控核心指标、做异常洞察或沉淀可复用的数据开发流程。",
    },
    {
        "group_id": "ml_tooling",
        "category": "AI / ML",
        "skills": ["PyTorch", "TensorFlow", "Deep Learning", "Generative AI", "NLP", "Model Deployment", "ML Infrastructure", "Prompt Engineering", "Computer Vision", "Keras", "OpenAI", "Context Engineering", "Embeddings", "OpenAI API", "Azure OpenAI", "LLM Application Development", "LangChain", "MLOps", "Retrieval Evaluation"],
        "common_introduction": "这组技术栈主要用于 AI 应用开发、模型训练部署和大模型能力集成，覆盖从算法到落地的完整链路。",
        "common_business_scenario": "团队通常会用它们构建智能问答、文本处理、推荐排序、审核辅助或模型运维体系，让 AI 能力真正进入日常业务流程。",
    },
    {
        "group_id": "infra_tooling",
        "category": "Cloud / DevOps / Infrastructure",
        "skills": ["Azure", "Linux", "GCP", "Shell", "Jenkins", "Terraform", "Bash", "Prometheus", "ECS", "GitLab CI", "Ansible"],
        "common_introduction": "这组技术栈主要面向部署运维、环境管理、自动化交付和系统可观测性，是生产系统稳定运行的基础设施层能力。",
        "common_business_scenario": "团队通常会用它们配置运行环境、自动发布服务、监控系统健康状态，并保障核心业务在持续迭代中保持稳定。",
    },
    {
        "group_id": "storage_streaming",
        "category": "Databases / Storage / Streaming",
        "skills": ["MongoDB", "NoSQL", "Cassandra", "Flink", "Elasticsearch", "DynamoDB", "Redshift", "Azure Blob Storage", "DB2", "SSMS"],
        "common_introduction": "这组技术栈主要用于数据存储、检索、流式处理和数据平台管理，覆盖结构化与非结构化数据场景。",
        "common_business_scenario": "团队通常会用它们保存业务记录、支撑查询检索、处理实时事件流，或为分析与监控链路提供底层数据能力。",
    },
    {
        "group_id": "systems_concepts",
        "category": "Architecture / Systems",
        "skills": ["Algorithms", "Data Structures", "Distributed Systems", "System Design", "Embedded Systems", "Networking", "Network Protocol", "Large-Scale Systems"],
        "common_introduction": "这组内容属于系统设计与工程基础能力，决定了一个系统在性能、可靠性、扩展性和实现复杂度上的上限。",
        "common_business_scenario": "团队通常会在设计高并发平台、复杂业务链路或需要长期演进的基础设施时依赖这些能力做技术决策。",
    },
    {
        "group_id": "engineering_workflow",
        "category": "Quality & Workflow",
        "skills": ["Scrum", "Unit Testing", "Jira", "TDD", "Agile", "pytest", "JUnit", "Code Review", "Playwright", "Software Test Engineering", "Selenium", "Design Review", "Cypress", "Jest", "Visual Studio"],
        "common_introduction": "这组技术栈和实践主要用于保障研发协作质量、提升交付效率，并降低代码与发布过程中的风险。",
        "common_business_scenario": "团队通常会用它们组织需求迭代、执行测试验证、评审代码与设计方案，从而让业务功能更稳定地上线和维护。",
    },
]

SKILL_FOCUS = {
    "Python": "通用性强，兼顾后端开发、数据处理、自动化和机器学习落地。",
    "Go": "偏向高并发服务、基础设施工具和性能稳定的后端系统。",
    "Java": "偏向企业级后端服务、复杂业务系统和长期维护型平台。",
    "JavaScript": "偏向 Web 交互逻辑，也常用于全栈应用和轻量服务开发。",
    "C++": "偏向高性能、底层能力和资源敏感型系统实现。",
    "Scala": "偏向数据平台、函数式风格开发和分布式计算生态。",
    "TypeScript": "偏向大型前后端工程中的类型安全和代码可维护性。",
    "R": "偏向统计分析、实验研究和数据探索型工作。",
    "C#": "偏向微软技术栈下的业务系统和桌面/后端应用。",
    "PHP": "偏向 Web 应用和传统站点后端开发。",
    "Ruby": "偏向快速业务开发和以 Rails 为代表的高迭代后端场景。",
    "Rust": "偏向安全性和性能要求较高的系统工具与服务。",
    "Kotlin": "偏向现代 JVM 开发，也常用于 Android 应用构建。",
    "Swift": "偏向 Apple 生态下的客户端与应用开发。",
    "MATLAB": "偏向数值计算、建模仿真和工程研究场景。",
    "VB.NET": "偏向传统企业内部系统和部分桌面应用维护。",
    "REST APIs": "强调标准化 HTTP 接口设计和跨系统集成能力。",
    "gRPC": "强调强类型、低延迟和服务间高性能调用。",
    "Microservices": "强调业务拆分、独立部署和服务自治。",
    "Flask": "强调轻量、灵活，适合快速搭建内部工具或小型 API。",
    "Node.js": "强调事件驱动和 JavaScript 统一栈开发体验。",
    "Spring Boot": "强调快速搭建生产级 Java 服务和完整生态支持。",
    "Spring": "强调企业级依赖注入、事务管理和大型后端架构能力。",
    "Express": "强调轻量 Node.js 服务开发和接口灵活性。",
    ".NET": "强调企业应用开发、工具链完整和微软生态整合。",
    "ASP.NET": "强调 Web 服务和企业后台开发能力。",
    "Rails": "强调约定优于配置和业务快速迭代。",
    "GraphQL": "强调按需取数和前后端灵活数据契约。",
    "FastAPI": "强调 Python 服务开发效率、类型提示和高性能接口。",
    "Django": "强调功能完备、后台能力强和成熟 Web 开发范式。",
    "NestJS": "强调结构化 Node.js 后端架构和工程规范。",
    ".NET / C#": "强调 .NET 平台能力与 C# 语言结合的企业开发场景。",
    "ASP.NET MVC": "强调经典 MVC Web 架构和服务端页面组织。",
    "React": "强调组件化、状态管理和交互式页面开发。",
    "Angular": "强调大型前端工程规范和完整框架能力。",
    "CSS": "强调页面样式控制和视觉呈现。",
    "HTML": "强调页面结构定义和内容组织。",
    "Vue": "强调渐进式接入和较低上手成本。",
    "HTML5": "强调现代 Web 标准能力和多媒体/语义化支持。",
    "Vite": "强调前端开发启动速度和构建效率。",
    "CSS3": "强调更丰富的样式、动画和布局能力。",
    "Next.js": "强调 React 生态下的全栈渲染与应用框架能力。",
    "Android SDK": "强调 Android 原生能力调用和移动端应用开发。",
    "Jetpack Compose": "强调声明式 Android UI 开发。",
    "Material Design": "强调统一设计规范和组件体验一致性。",
    "Tailwind": "强调原子化样式和高效率页面搭建。",
    "Webpack": "强调前端资源打包与构建流程控制。",
    "SQL": "强调结构化查询、聚合分析和数据口径校验。",
    "Pandas": "强调灵活的数据清洗、拼接和探索分析能力。",
    "Spark SQL": "强调大规模数据的分布式查询与聚合处理。",
    "Hive": "强调离线数仓查询和批量数据组织。",
    "ETL": "强调把原始数据加工成可消费数据资产的流程能力。",
    "A/B Testing": "强调实验设计、效果比较和决策验证。",
    "Airflow": "强调定时调度、任务依赖和数据工作流编排。",
    "Jupyter": "强调交互式分析和探索式数据研究。",
    "Spark": "强调大规模分布式数据处理能力。",
    "Tableau": "强调商业分析看板和可视化呈现。",
    "Data Pipelines": "强调数据从采集到消费的链路建设。",
    "Matplotlib": "强调基础图表绘制和分析结果展示。",
    "Snowflake": "强调云数仓能力和多团队数据共享。",
    "Databricks": "强调数据工程与机器学习一体化平台能力。",
    "BigQuery": "强调云上大规模 SQL 分析能力。",
    "NumPy": "强调数值计算和数组运算基础。",
    "Power BI": "强调业务报表制作和自助分析能力。",
    "dbt": "强调数据模型管理、转换治理和版本化开发。",
    "Hadoop": "强调分布式存储与批处理基础设施。",
    "Anomaly Detection": "强调异常模式识别和监控告警支撑。",
    "Dashboard Automation": "强调报表自动刷新和分析流程自动化。",
    "Experiment Design": "强调实验方法论和指标因果评估。",
    "Forecasting": "强调趋势预测和经营计划支持。",
    "KPI Measurement": "强调关键指标定义、计算与跟踪。",
    "Looker": "强调指标层建模和数据消费统一视图。",
    "Time Series Analysis": "强调时间序列规律挖掘与预测。",
    "RAG": "强调把外部知识检索结果注入模型回答过程。",
    "AWS Bedrock": "强调企业环境中的托管模型接入与治理。",
    "LLM": "强调自然语言理解、生成和复杂文本任务处理。",
    "scikit-learn": "强调传统机器学习建模与评估效率。",
    "Machine Learning": "强调利用数据驱动预测和自动化决策。",
    "PyTorch": "强调灵活的深度学习建模与研究迭代。",
    "TensorFlow": "强调生产化深度学习训练与部署生态。",
    "Deep Learning": "强调神经网络建模和复杂模式学习。",
    "Generative AI": "强调内容生成、智能助手和创作型 AI 场景。",
    "NLP": "强调文本理解、分类、抽取和语言处理。",
    "Model Deployment": "强调模型上线、推理服务和版本管理。",
    "ML Infrastructure": "强调训练、评估、发布和监控的基础设施建设。",
    "Prompt Engineering": "强调针对大模型任务设计高质量提示词。",
    "Computer Vision": "强调图像识别、检测和视觉理解任务。",
    "Keras": "强调高层次深度学习建模开发效率。",
    "OpenAI": "强调模型能力调用和通用大模型能力接入。",
    "Context Engineering": "强调上下文组织、信息压缩和输入设计。",
    "Embeddings": "强调向量表示、语义相似度和召回能力。",
    "OpenAI API": "强调通过接口把大模型能力集成进业务系统。",
    "Azure OpenAI": "强调在 Azure 环境中接入大模型能力。",
    "LLM Application Development": "强调围绕大模型构建完整业务应用。",
    "LangChain": "强调多组件编排和 LLM 应用开发框架化。",
    "MLOps": "强调机器学习系统的工程化与运营管理。",
    "Retrieval Evaluation": "强调检索质量度量与 RAG 效果评估。",
    "Docker": "强调环境一致性、容器化交付和服务可移植性。",
    "Kubernetes": "强调容器编排、弹性伸缩和集群管理。",
    "AWS": "强调云资源供给完整和托管服务生态丰富。",
    "CI/CD": "强调自动化校验、发布和持续交付。",
    "GitHub Actions": "强调仓库内自动化流程和发布流水线集成。",
    "Azure": "强调微软云生态和企业级云资源管理。",
    "Linux": "强调服务器运行环境和系统层运维基础。",
    "GCP": "强调 Google 云服务与数据/AI 生态协同。",
    "Shell": "强调脚本化自动化和系统任务串联。",
    "Jenkins": "强调可定制化持续集成与传统流水线建设。",
    "Terraform": "强调基础设施即代码和跨环境资源管理。",
    "Bash": "强调命令行自动化和运维脚本执行。",
    "Prometheus": "强调指标采集、监控与告警体系建设。",
    "ECS": "强调容器运行和云上服务编排。",
    "GitLab CI": "强调 GitLab 体系内的自动化测试与部署。",
    "Ansible": "强调批量配置管理和自动化运维。",
    "PostgreSQL": "强调事务能力、复杂查询和稳定关系型存储。",
    "Kafka": "强调高吞吐事件流和异步解耦。",
    "Redis": "强调高速缓存、会话状态和热点数据访问。",
    "MySQL": "强调通用事务型应用存储和成熟生态。",
    "S3": "强调对象存储、文件归档和大规模数据落盘。",
    "MongoDB": "强调文档型存储和灵活模式设计。",
    "NoSQL": "强调非关系型数据模型和水平扩展能力。",
    "Cassandra": "强调分布式高可用写入与大规模数据承载。",
    "Flink": "强调实时流处理和低延迟计算。",
    "Elasticsearch": "强调全文检索和快速查询分析。",
    "DynamoDB": "强调云原生键值存储和高可扩展性。",
    "Redshift": "强调云数仓分析和大规模聚合查询。",
    "Azure Blob Storage": "强调 Azure 生态下的对象存储能力。",
    "DB2": "强调传统企业数据库和大型系统兼容性。",
    "SSMS": "强调 SQL Server 管理与开发工具支持。",
    "Algorithms": "强调效率优化、问题建模和核心逻辑设计。",
    "Data Structures": "强调数据组织方式和算法实现基础。",
    "Distributed Systems": "强调多节点协作、一致性与容错能力。",
    "System Design": "强调高层架构规划和模块边界设计。",
    "Embedded Systems": "强调软硬件结合和资源受限场景开发。",
    "Networking": "强调网络通信原理和链路设计理解。",
    "Network Protocol": "强调协议规则、传输机制和系统互通。",
    "Large-Scale Systems": "强调大规模流量、容量和复杂链路治理。",
    "Git": "强调版本管理、协作开发和变更追踪。",
    "Scrum": "强调敏捷迭代节奏和跨职能协作。",
    "Unit Testing": "强调单元级验证和代码正确性保障。",
    "Jira": "强调需求、任务和缺陷流程管理。",
    "TDD": "强调测试先行和可验证开发方式。",
    "Agile": "强调快速反馈、持续迭代和业务协同。",
    "pytest": "强调 Python 生态下的自动化测试效率。",
    "JUnit": "强调 Java 生态下的单元测试规范。",
    "Code Review": "强调变更评审、知识共享和质量把关。",
    "Playwright": "强调端到端自动化测试和浏览器交互验证。",
    "Software Test Engineering": "强调测试体系建设和质量流程设计。",
    "Selenium": "强调浏览器自动化和回归测试场景。",
    "Design Review": "强调方案评审和架构风险前置识别。",
    "Cypress": "强调前端集成测试和页面交互验证。",
    "Jest": "强调 JavaScript/前端单元测试能力。",
    "Visual Studio": "强调 .NET 等生态下的集成开发环境支持。",
}

SKILL_FOCUS.update(
    {
        "C": "偏向底层系统、性能敏感模块和贴近硬件的工程实现。",
        "APIs": "强调系统接口抽象、调用契约与服务协作边界。",
        "Web Development": "强调 Web 产品开发全流程与页面到服务的联动实现。",
        "Backend Development": "强调服务端业务逻辑、数据访问和接口交付。",
        "Full-Stack Development": "强调从前端页面到后端服务的一体化交付能力。",
        "Data Science": "强调统计建模、实验分析和数据驱动问题求解。",
        "Relational Databases": "强调结构化数据建模、事务一致性与关系查询能力。",
        "Object-Oriented Programming": "强调抽象建模、封装复用和大型代码结构组织。",
        "Version Control": "强调多人协作下的版本管理、分支策略和变更追踪。",
        "Software Testing": "强调通过自动化与工程流程降低功能回归和线上风险。",
    }
)

BUSINESS_GROUPS = [
    {
        "group_id": "backend_delivery",
        "group_label": "后端服务与业务接口交付",
        "category": "Backend & APIs",
        "skills": [
            "Python",
            "Go",
            "C",
            "C++",
            "Java",
            "JavaScript",
            "TypeScript",
            "C#",
            "Scala",
            "PHP",
            "Ruby",
            "Rust",
            "VB.NET",
            "Node.js",
            "Spring Boot",
            "Spring",
            "Express",
            "Flask",
            "FastAPI",
            "Django",
            "Rails",
            "NestJS",
            ".NET",
            "ASP.NET",
            "ASP.NET MVC",
            ".NET / C#",
            "GraphQL",
            "REST APIs",
            "gRPC",
            "APIs",
            "Web Development",
            "Backend Development",
            "Full-Stack Development",
            "Microservices",
            "PostgreSQL",
            "MySQL",
            "Redis",
            "Kafka",
            "Git",
            "CI/CD",
        ],
        "common_introduction": "这组技术栈主要用于后端服务、接口设计和业务系统交付，覆盖从服务实现到系统联调的核心工程能力。",
        "common_business_scenario": "团队通常会用它们开发订单、账户、支付、权限、工单等核心服务，并对接上游页面和下游数据或基础设施系统。",
    },
    {
        "group_id": "data_analytics",
        "group_label": "数据分析与经营决策支持",
        "category": "Data & Analytics",
        "skills": [
            "Python",
            "R",
            "MATLAB",
            "SQL",
            "Pandas",
            "Spark SQL",
            "Hive",
            "ETL",
            "Airflow",
            "Spark",
            "Jupyter",
            "Tableau",
            "Data Pipelines",
            "Matplotlib",
            "Snowflake",
            "Databricks",
            "BigQuery",
            "NumPy",
            "Power BI",
            "dbt",
            "Hadoop",
            "Data Science",
            "A/B Testing",
            "Experiment Design",
            "Forecasting",
            "KPI Measurement",
            "Dashboard Automation",
            "Time Series Analysis",
            "Anomaly Detection",
            "Looker",
            "Git",
        ],
        "common_introduction": "这组技术栈围绕数据加工、指标建设、实验分析和报表消费展开，是数据驱动型业务决策的核心支撑能力。",
        "common_business_scenario": "团队通常会用它们建设数仓与报表链路、做转化分析和经营复盘，并为产品、运营和管理层提供可执行的数据结论。",
    },
    {
        "group_id": "ai_ml_productization",
        "group_label": "AI/ML 应用开发与模型落地",
        "category": "AI / ML",
        "skills": [
            "Python",
            "SQL",
            "Pandas",
            "Machine Learning",
            "Deep Learning",
            "LLM",
            "LLM Application Development",
            "RAG",
            "AWS Bedrock",
            "scikit-learn",
            "PyTorch",
            "TensorFlow",
            "Keras",
            "NLP",
            "Computer Vision",
            "Generative AI",
            "Embeddings",
            "Prompt Engineering",
            "OpenAI",
            "OpenAI API",
            "Azure OpenAI",
            "LangChain",
            "MLOps",
            "Model Deployment",
            "ML Infrastructure",
            "Retrieval Evaluation",
            "Context Engineering",
            "Docker",
            "Kubernetes",
            "Airflow",
            "Git",
            "CI/CD",
        ],
        "common_introduction": "这组技术栈主要服务于 AI/ML 能力建设，从模型训练、评估、部署到大模型应用编排都涵盖在内。",
        "common_business_scenario": "团队通常会用它们构建检索问答、文本理解、智能审核、推荐排序或运营辅助系统，并让模型能力稳定进入日常业务流程。",
    },
    {
        "group_id": "frontend_experience",
        "group_label": "前端体验与产品交互实现",
        "category": "Frontend & UI",
        "skills": [
            "JavaScript",
            "TypeScript",
            "React",
            "Angular",
            "Vue",
            "Next.js",
            "HTML",
            "HTML5",
            "CSS",
            "CSS3",
            "Tailwind",
            "Vite",
            "Webpack",
            "GraphQL",
            "Node.js",
            "Web Development",
            "Full-Stack Development",
            "Git",
            "CI/CD",
        ],
        "common_introduction": "这组技术栈主要用于构建用户直接感知的交互层，包括页面结构、视觉样式、前端工程化和前后端联动能力。",
        "common_business_scenario": "团队通常会用它们开发管理后台、客户门户、运营工作台和增长页面，承接信息展示、操作提交与状态反馈等核心交互场景。",
    },
    {
        "group_id": "platform_devops",
        "group_label": "平台工程、DevOps 与稳定性保障",
        "category": "Cloud / DevOps / Infrastructure",
        "skills": [
            "Go",
            "Python",
            "Linux",
            "Shell",
            "Bash",
            "Terraform",
            "Docker",
            "Kubernetes",
            "AWS",
            "Azure",
            "GCP",
            "S3",
            "Prometheus",
            "ECS",
            "Jenkins",
            "GitHub Actions",
            "GitLab CI",
            "Ansible",
            "CI/CD",
            "Git",
            "Kafka",
            "Redis",
        ],
        "common_introduction": "这组技术栈围绕环境管理、自动化交付、可观测性和平台稳定性展开，是生产系统长期可靠运行的基础设施能力集合。",
        "common_business_scenario": "团队通常会用它们部署服务、配置资源、建设发布流水线、监控线上健康度，并保障高峰期业务系统可扩展且可恢复。",
    },
    {
        "group_id": "storage_streaming",
        "group_label": "数据存储、检索与流式处理",
        "category": "Databases / Storage / Streaming",
        "skills": [
            "SQL",
            "Relational Databases",
            "PostgreSQL",
            "MySQL",
            "MongoDB",
            "NoSQL",
            "Cassandra",
            "DynamoDB",
            "Redis",
            "S3",
            "Kafka",
            "Flink",
            "Elasticsearch",
            "Redshift",
            "Azure Blob Storage",
            "DB2",
            "SSMS",
        ],
        "common_introduction": "这组技术栈主要负责业务数据的持久化、查询检索、事件流转与分析承载，是应用系统和数据平台的底座。",
        "common_business_scenario": "团队通常会用它们保存交易和状态数据、支撑全文检索与实时报文流，并为下游报表、监控和智能应用提供稳定数据来源。",
    },
    {
        "group_id": "engineering_quality",
        "group_label": "工程协作、测试与发布质量",
        "category": "Quality & Workflow",
        "skills": [
            "Git",
            "Version Control",
            "CI/CD",
            "GitHub Actions",
            "GitLab CI",
            "Jenkins",
            "Unit Testing",
            "Software Testing",
            "pytest",
            "JUnit",
            "Playwright",
            "Selenium",
            "Cypress",
            "Jest",
            "TDD",
            "Code Review",
            "Design Review",
            "Software Test Engineering",
            "Scrum",
            "Agile",
            "Jira",
            "Visual Studio",
        ],
        "common_introduction": "这组技术栈和实践围绕团队协作、测试验证、持续交付和质量治理展开，目标是降低变更风险并提升交付效率。",
        "common_business_scenario": "团队通常会用它们组织开发流程、执行自动化测试、评审代码和方案，并让业务功能以更稳定可控的方式进入生产环境。",
    },
    {
        "group_id": "systems_foundations",
        "group_label": "系统设计与工程基础能力",
        "category": "Architecture / Systems",
        "skills": [
            "Algorithms",
            "Data Structures",
            "Distributed Systems",
            "System Design",
            "Object-Oriented Programming",
            "Networking",
            "Network Protocol",
            "Large-Scale Systems",
            "Embedded Systems",
            "Microservices",
            "APIs",
            "REST APIs",
            "gRPC",
        ],
        "common_introduction": "这组能力决定了工程师如何设计高性能、可扩展且可维护的软件系统，是很多应用技术之上的通用基础。",
        "common_business_scenario": "团队通常会在设计复杂链路、高并发平台、服务拆分方案或长期演进的系统架构时依赖这些基础能力做技术取舍。",
    },
    {
        "group_id": "mobile_client",
        "group_label": "移动端与客户端体验建设",
        "category": "Frontend & UI",
        "skills": [
            "Kotlin",
            "Swift",
            "Android SDK",
            "Jetpack Compose",
            "Material Design",
            "React",
            "TypeScript",
            "HTML",
            "CSS",
            "Git",
            "CI/CD",
        ],
        "common_introduction": "这组技术栈主要服务于移动端和客户端产品体验建设，覆盖原生能力、界面组织和交付协作链路。",
        "common_business_scenario": "团队通常会用它们开发移动应用界面、优化客户端交互体验，并与后端服务和发布流程协同完成版本迭代。",
    },
]

_MERGED_GROUP_BY_SKILL = {
    skill: group["group_id"]
    for group in MERGED_GROUPS
    for skill in group["skills"]
}


def describe_skill(skill: str, category: str) -> tuple[str, str]:
    override = SKILL_OVERRIDES.get(skill)
    if override is not None:
        return override
    intro_template, scenario_template = CATEGORY_DEFAULTS[category]
    return (
        intro_template.format(skill=skill),
        scenario_template.format(skill=skill),
    )


def skill_focus(skill: str) -> str:
    return SKILL_FOCUS.get(skill, "偏向该类技术栈中的通用能力与常规业务落地场景。")


def merged_group_id(skill: str) -> str | None:
    return _MERGED_GROUP_BY_SKILL.get(skill)


def merged_group_definitions() -> list[dict[str, object]]:
    return MERGED_GROUPS


def business_group_definitions() -> list[dict[str, object]]:
    return BUSINESS_GROUPS


def validate_categories(categories: list[str]) -> None:
    if categories != CATEGORY_ORDER:
        raise ValueError("Description generator expects taxonomy category order to stay aligned.")
